### ISSUE TITLE
Issue with whitelist

### ISSUE THREAD

**Issue by ESLRetr0** [kyb3r/logviewer#14]
I don't understand what the website is for OAUTH2_REDIRECT_URI. Any help would be appreciated!
:)

**Comment by papiersnipper** [comment]
This will be equal to the url of your log viewer app + `/callback`, e.g. `https://logviewer.herokuapp.com/callback`. You will need to add this same url as a redirect url in the oauth2 section in the discord dev portal.

![image](https://camo.githubusercontent.com/4d76a0a5c6dd21d0934743a9fda3e84cefa54895/68747470733a2f2f692e696d6775722e636f6d2f65765a4957594e2e706e67)

**Comment by ESLRetr0** [comment]
Oh ok, it makes sense now. Thx for the reply!
